-- examiner_reports.sql
-- Owned by: Examiner Report Agent (reports, observations), Misconception Agent (misconceptions, interventions)
-- Purpose: Examiner observations, recurring mistakes, misconception database

PRAGMA foreign_keys = ON;
PRAGMA journal_mode = WAL;

-- One row per examiner report document
-- paper_id references question_bank.db papers.id
CREATE TABLE IF NOT EXISTS reports (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    paper_id        INTEGER NOT NULL UNIQUE,    -- FK to question_bank.db papers.id
    year            INTEGER NOT NULL,
    session         TEXT NOT NULL,              -- e.g., "January 2023"
    subject         TEXT NOT NULL,
    module_code     TEXT NOT NULL,
    raw_text        TEXT,                       -- full extracted text
    processed_at    TEXT NOT NULL               -- ISO 8601 datetime
);

-- Individual observations extracted from a report, linked to questions
CREATE TABLE IF NOT EXISTS observations (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    report_id       INTEGER NOT NULL REFERENCES reports(id),
    question_id     INTEGER,                    -- FK to question_bank.db questions.id (nullable if general)
    topic           TEXT,
    subtopic        TEXT,
    observation_type TEXT NOT NULL
                    CHECK(observation_type IN (
                        'common_error','misconception','weak_area',
                        'command_word_failure','positive_note','emphasis'
                    )),
    description     TEXT NOT NULL,
    emphasis_level  INTEGER NOT NULL DEFAULT 1 CHECK(emphasis_level BETWEEN 1 AND 3)
                    -- 1=mentioned, 2=highlighted, 3=strongly emphasized
);

-- Persistent misconception records (aggregated across reports)
-- spec_point_id references progress.db specification_points.id
CREATE TABLE IF NOT EXISTS misconceptions (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    subject         TEXT NOT NULL,
    module_code     TEXT NOT NULL,
    topic           TEXT NOT NULL,
    subtopic        TEXT,
    spec_point_id   INTEGER,                    -- FK to progress.db specification_points.id
    description     TEXT NOT NULL,
    frequency       INTEGER NOT NULL DEFAULT 1, -- how many reports mention this
    last_seen       TEXT NOT NULL,              -- ISO 8601 date of most recent report mentioning it
    is_active       INTEGER NOT NULL DEFAULT 1 CHECK(is_active IN (0,1)),
    UNIQUE(subject, module_code, topic, description)
);

-- Links misconceptions to their source observations
CREATE TABLE IF NOT EXISTS misconception_sources (
    misconception_id    INTEGER NOT NULL REFERENCES misconceptions(id),
    observation_id      INTEGER NOT NULL REFERENCES observations(id),
    PRIMARY KEY(misconception_id, observation_id)
);

-- Corrective interventions generated by Misconception Agent
CREATE TABLE IF NOT EXISTS corrective_interventions (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    misconception_id INTEGER NOT NULL REFERENCES misconceptions(id),
    intervention_text TEXT NOT NULL,
    intervention_type TEXT NOT NULL
                    CHECK(intervention_type IN ('explanation','worked_example','common_trap_warning','question_set')),
    created_at      TEXT NOT NULL               -- ISO 8601 datetime
);

CREATE INDEX IF NOT EXISTS idx_observations_report ON observations(report_id);
CREATE INDEX IF NOT EXISTS idx_observations_type ON observations(observation_type);
CREATE INDEX IF NOT EXISTS idx_misconceptions_subject ON misconceptions(subject, module_code);
CREATE INDEX IF NOT EXISTS idx_misconceptions_topic ON misconceptions(topic);
CREATE INDEX IF NOT EXISTS idx_misconceptions_active ON misconceptions(is_active);
